version: "3.3"

services:
  ember:
    container_name: ember
    image: ember
    build: ./dockerfiles/ember
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cache
      - database
    volumes:
      - "./volumes/html/:/var/www/html/"
      - "./volumes/assets/:/var/www/assets/"
    env_file: .env
    environment:
      DISCORD_HOST: "http://discord:3000"

  discord:
    container_name: ember-discord-bot
    image: ember-discord-bot
    build: ./dockerfiles/discord
    restart: always
    depends_on:
      - ember
    volumes:
      - "./volumes/discord/:/app/"
    env_file: .env
    environment:
      DB_HOST: ""
      DB_PORT: ""
      DB_DATABASE: ""
      DB_USERNAME: ""
      DB_PASSWORD: ""

  database:
    container_name: ember-database
    image: mysql:5
    restart: always
    env_file: .env
    volumes:
      - "./volumes/database:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: $DB_PORT
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  cache:
    container_name: ember-cache
    image: redis:alpine
    restart: always
    volumes:
        - "./volumes/cache:/data"
